
export const SUPPORTED_LANGUAGES = {
  EN: 'English',
  ES: 'Spanish',
  DE: 'Deutsch',
  BG: 'Bulgarian',
  CS: 'Czech',
  DA: 'Danish',
  EL: 'Greek',
  ET: 'Estonian',
  FI: 'Finnish',
  FR: 'French',
  HU: 'Hungarian',
  ID: 'Indonesian',
  IT: 'Italian',
  JA: 'Japanese',
  KO: 'Korean',
  LT: 'Lithuanian',
  LV: 'Latvian',
  NB: 'Norwegian',
  NL: 'Dutch',
  PL: 'Polish',
  PT: 'Portuguese',
  RO: 'Romanian',
  RU: 'Russian',
  SK: 'Slovak',
  SL: 'Slovenian',
  SV: 'Swedish',
  TR: 'Turkish',
  UK: 'Ukrainian',
  ZH: 'Chinese'
}

export const VOICE_TAG_FOR_LANGUAGE = {
  auto: 'en-GB',
  EN: 'en-GB',
  ES: 'es-MX',
  DE: 'de-DE',
  BG: 'en-GB',
  CS: 'cs-CZ',
  DA: 'da-DK',
  EL: 'el-GR',
  ET: 'en-GB',
  FI: 'fi-FI',
  FR: 'fr-FR',
  HU: 'hu-HU',
  ID: 'id-ID',
  IT: 'it-IT',
  JA: 'ja-JP',
  KO: 'ko-KR',
  LT: 'en-GB',
  LV: 'en-GB',
  NB: 'no-NO',
  NL: 'nl-NL',
  PL: 'pl-PL',
  PT: 'pt-BR',
  RO: 'ro-RO',
  RU: 'ru-RU',
  SK: 'sk-SK',
  SL: 'en-GB',
  SV: 'sv-SE',
  TR: 'tr-TR',
  UK: 'en-GB',
  ZH: 'zh-CN'
}

export const AUTO_LANGUAGE = 'auto'
